library(glmnet)  
training_features <- read.table("feature.csv", sep = ",", head = T,row.names=1)  
fitx <- as.matrix(training_features[,2:189])  
fity <- as.matrix(training_features[,1])  
fit <- glmnet(fitx,fity,family = "binomial")  
plot(fit,xvar = "lambda",label = TRUE)  
abline(v=-3.2956410552,lty=3)  
set.seed(1111)  
cvfit <- cv.glmnet(fitx,fity,family="binomial",type.measure="deviance",nfolds=10)  
plot(cvfit,xlim=c(-6.8,-2))  
c(cvfit$lambda.min, cvfit$lambda.1se)  
coef(cvfit,s=c(cvfit$lambda.min))  

pred<-predict(cvfit, newx=fitx, type="link", s="lambda.min")  
write.table(pred,file = "pred.csv",sep = ",")